name: retaurant_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.0
  flutter_native_splash: ^0.3.2
  get: ^3.26.0
  google_fonts: ^1.1.2
  http: ^0.12.0+2
  provider: ^5.0.0
  supercharged: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"
  flutter_launcher_name: "^0.0.1"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/store.png"

flutter_launcher_name:
  name: "Restaurant App"

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/local_restaurant.json
